from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from .errors import AbhError
from .storage import root_dir, write_text


CODEX_CONFIG_PATH = ".codex/config.toml"
MANAGED_MARKER = "ABH MANAGED CODEX CONFIG"

DEVELOPER_INSTRUCTIONS = """Use `skills/abh-workflow` for this repository.
Before choosing implementation work, run:
- `abh onboarding check --json`
- `abh next --json`
- `abh doctor --json`
- `abh roadmap check --json`
Follow ABH plan, verification, audit, close, and memory rules for all repository work.
Treat unmanaged `.codex/config.toml` as user-owned state and do not replace it without explicit user action.
"""


@dataclass(frozen=True, slots=True)
class CodexAction:
    path: str
    kind: str
    reason: str

    def to_dict(self) -> dict[str, str]:
        return {"path": self.path, "kind": self.kind, "reason": self.reason}


def _codex_config_path(root: Path) -> Path:
    return root / CODEX_CONFIG_PATH


def _managed_content() -> str:
    return (
        f"# {MANAGED_MARKER}\n"
        "# Generated by `abh codex on`; rerun that command to refresh this file.\n\n"
        'developer_instructions = """\n'
        f"{DEVELOPER_INSTRUCTIONS}"
        '"""\n'
    )


def _is_managed(content: str) -> bool:
    return MANAGED_MARKER in content


def codex_status(*, cwd: Path | None = None) -> dict[str, object]:
    root = root_dir(cwd)
    config_path = _codex_config_path(root)
    if not config_path.exists():
        return {
            "enabled": False,
            "managed": False,
            "state": "absent",
            "mode": "status",
            "path": CODEX_CONFIG_PATH,
            "write": False,
            "confirmed": False,
            "writes": [],
            "blockers": [],
        }

    content = config_path.read_text(encoding="utf-8")
    if _is_managed(content):
        return {
            "enabled": True,
            "managed": True,
            "state": "managed",
            "mode": "status",
            "path": CODEX_CONFIG_PATH,
            "write": False,
            "confirmed": False,
            "writes": [],
            "blockers": [],
        }

    return {
        "enabled": False,
        "managed": False,
        "state": "unmanaged",
        "mode": "status",
        "path": CODEX_CONFIG_PATH,
        "write": False,
        "confirmed": False,
        "writes": [],
        "blockers": [CodexAction(path=CODEX_CONFIG_PATH, kind="file", reason="existing unmanaged Codex config").to_dict()],
    }


def preview_codex_on(*, cwd: Path | None = None, write: bool = False, confirmed: bool = False) -> dict[str, object]:
    root = root_dir(cwd)
    config_path = _codex_config_path(root)
    writes: list[CodexAction] = []
    blockers: list[CodexAction] = []
    status = codex_status(cwd=root)

    if not config_path.exists():
        writes.append(CodexAction(path=CODEX_CONFIG_PATH, kind="file", reason="install managed Codex ABH config"))
    else:
        content = config_path.read_text(encoding="utf-8")
        if _is_managed(content):
            writes.append(CodexAction(path=CODEX_CONFIG_PATH, kind="file", reason="refresh managed Codex ABH config"))
        else:
            blockers.append(CodexAction(path=CODEX_CONFIG_PATH, kind="file", reason="existing unmanaged Codex config; will not overwrite"))

    return {
        "enabled": bool(status["enabled"]),
        "managed": bool(status["managed"]),
        "state": status["state"],
        "mode": "write" if write else "preview",
        "path": CODEX_CONFIG_PATH,
        "write": write,
        "confirmed": confirmed,
        "writes": [action.to_dict() for action in writes],
        "blockers": [action.to_dict() for action in blockers],
    }


def codex_on(*, cwd: Path | None = None, write: bool = False, confirmed: bool = False) -> dict[str, object]:
    if write and not confirmed:
        raise AbhError("abh codex on --write requires --confirm")

    root = root_dir(cwd)
    result = preview_codex_on(cwd=root, write=write, confirmed=confirmed)
    if result["blockers"] and write:
        raise AbhError("existing unmanaged Codex config at .codex/config.toml; will not overwrite")
    if not write:
        return result

    write_text(_codex_config_path(root), _managed_content())
    return {
        **result,
        "enabled": True,
        "managed": True,
        "state": "managed",
    }


def preview_codex_off(*, cwd: Path | None = None, write: bool = False, confirmed: bool = False) -> dict[str, object]:
    root = root_dir(cwd)
    config_path = _codex_config_path(root)
    writes: list[CodexAction] = []
    blockers: list[CodexAction] = []
    status = codex_status(cwd=root)

    if config_path.exists():
        content = config_path.read_text(encoding="utf-8")
        if _is_managed(content):
            writes.append(CodexAction(path=CODEX_CONFIG_PATH, kind="file", reason="remove managed Codex ABH config"))
        else:
            blockers.append(CodexAction(path=CODEX_CONFIG_PATH, kind="file", reason="existing unmanaged Codex config; will not remove"))

    return {
        "enabled": bool(status["enabled"]),
        "managed": bool(status["managed"]),
        "state": status["state"],
        "mode": "write" if write else "preview",
        "path": CODEX_CONFIG_PATH,
        "write": write,
        "confirmed": confirmed,
        "writes": [action.to_dict() for action in writes],
        "blockers": [action.to_dict() for action in blockers],
    }


def codex_off(*, cwd: Path | None = None, write: bool = False, confirmed: bool = False) -> dict[str, object]:
    if write and not confirmed:
        raise AbhError("abh codex off --write requires --confirm")

    root = root_dir(cwd)
    result = preview_codex_off(cwd=root, write=write, confirmed=confirmed)
    if not write:
        return result
    if result["blockers"] or not result["writes"]:
        return {
            **result,
            "enabled": False,
            "managed": False,
        }

    _codex_config_path(root).unlink(missing_ok=True)
    return {
        **result,
        "enabled": False,
        "managed": False,
        "state": "absent",
    }
